### ISSUE TITLE
✨ Diagramm Needs to Zoom

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/charon#119]
## Describe your issue

Zoom should work, as in the Camunder Modeler.

## What is to do?

Implement it.

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by MiguelACarballo** [comment]
Function is implemented.
