### ISSUE TITLE
"Consuming a REST API"-Example ist not working as intended

### ISSUE THREAD

**Issue by heikomat** [process-engine/charon#12]
*-> Moved here from https://github.com/process-engine/documentation/issues/2*

#### Describe your issue

When I try to do the "Consuming a REST API"-Example (https://processenginejs.github.io/documentation/quick-start/hands-on/consuming-rest-api.html)
I'm not able to show the received Data. 
I followed the steps exactly like they are mentioned in the example, but when i click on "start" to process stops at the "User Task" but doesn't show any Data as expected.
The problem lies within the Function that handles the Data from the REST API.

#### How can others reproduce the issue?

Just follow the steps in the Example exactly like they are mentioned

#### Possible solution

"Charon" is handling the values of the "uiConfig" differently than the package "Process-Engine".
The correct way: https://github.com/process-engine/process_engine/blob/35a55fb0402f649efad245974646a0b687df0900/src/entity_types/node_instance.ts#L657
The not-so correct way (in Charon): https://github.com/process-engine/charon/blob/2dff0a599a17298170eb39f7140d677eb56f01da/src/modules/dynamic-ui/dynamic-ui.service.ts#L136

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ppoetschke** [comment]
Btw, the way of handling extension properties like uiConfig can be quite different between the process engine itself and a client like Charon.
The process engine is evaluating the string value of the extension property and tries to interpret it as an expression with references to the process token. This object is sent already serialized to the client-api over messagebus.
The client should therefore not load the nodeDefintion with the value expression by itself but rather should listen to usertask events, to get meaningful information. In case the client is reading directly nodeDefinition entities it must perform the evaluation by itself and load the processToken entity too.
I recommend to refactor this part to leave the evaluation inside of the process engine.

**Comment by heikomat** [comment]
@ppoetschke this is not possible, because the client might not be online when the process-engine sends the message over the messagebus.

For the task-list, the client has to be able to acuire the information needed to render the ui at any point in time, not only when the process-engine sends that info over the messagebus

**Comment by ppoetschke** [comment]
@heikomat This is surely possible as the client could send a request to the process engine, that it want to render a specific usertask. It simultaneously would listen to the appropriate event. We already used this approach in the react version of the workload list.
However this should be solved correctly by the next version of the client api and charon should use it then.

**Comment by heikomat** [comment]
@ppoetschke sure, this would work, but requesting a resource (in this case the ui-info) sounds more like a job for an http-request to me. As i understand it, the messagebus ist mostly there, so messages can be pushed rather than requested.

Wouldn't it be a more elegant solution to have an http-route that gives us the full ui-info, instead of using the messagebus?

**Comment by ppoetschke** [comment]
@heikomat Sure, this would be a requirement of the backend part of the new client api to support multiple protocols. I assume we would have clients not being able to support socket connections.

**Comment by heikomat** [comment]
for clarification: the "backend part of the new client api" does not describe a new client-api-backend-package, but rather the changes that a required in the existing backend-packages, so the client-api can do its job

**Comment by SORC3r3r** [comment]
Is the 'Sending mails' example not working because of the same reasons?

**Comment by heikomat** [comment]
@SORC3r3r yes, this is probably the case. Charon will very soon switch to use our new consumer_client, with wich this problem will be fixed

**Comment by Vyperus** [comment]
Since the Consumer Client is now implemented, this is working again ;)
