### ISSUE TITLE
✨ Needs Functionality to Create and Remove Space in Diagram

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/charon#120]
## Describe your issue

A tool should exist, that enables the user to create/remove space.

Compare and steal ideas from Camunda Modeler.

## What is to do?

Implement it; Create/Remove-Space-Tool.

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment]
This function is already implemented.
The tool looks like this:
<img width="38" alt="spacing-tool" src="https://user-images.githubusercontent.com/20394992/35044778-eae4eeb6-fb91-11e7-804f-b583659fca08.png">
