### ISSUE TITLE
Implement ClientAPI

### ISSUE THREAD

**Issue by Paulomart** [process-engine/charon#19]
#### Describe your issue

Currently the client api is work in process we should create a new branch implemention the new features from it.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

#### See

- https://github.com/process-engine/charon/tree/feature/consumer_client

**Comment by heikomat** [comment]
This was implemented in #29
