### ISSUE TITLE
Special characters in DefaultValue breaks export

### ISSUE THREAD

**Issue by SORC3r3r** [process-engine/charon#25]
#### Describe your issue

1. put a special character like ", <, > into e.g. uiName-Form Task DefaultValue
2. export 
3. exported document ends with **defaultValue="&** 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
@SORC3r3r i can't seem to reproduce your issue. Can you give me a little more detail? It would be helpful to know what browser you use, what exactly you did to make it break and what the process looks like (or at least the interesting part of it).

**Comment by heikomat** [comment]
@SORC3r3r i can now reproduce you issue. It seems to only happen in Firefox, not in chrome. I'm on it

**Comment by heikomat** [comment]
Fix is here: https://github.com/process-engine/charon/pull/26
