### ISSUE TITLE
Export BPMN Diagram with given name

### ISSUE THREAD

**Issue by ppoetschke** [process-engine/charon#27]
#### Describe your issue

When exporting a diagram the file name should be the name of the process and not the generic name 'Diagram'.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by sprengerjo** [comment]
can you also export the file as '.bpmn'?

**Comment by heikomat** [comment]
@sprengerjo that should be no problem. could you please quickly open a new issue for that, so we can't forget it?

**Comment by sprengerjo** [comment]
#49
