### ISSUE TITLE
mehr/bessere Buttons in Widgets

### ISSUE THREAD

**Issue by heikomat** [process-engine/charon#3]
Aktuell zeigen wir einen `Abbrechen` und `Weiter` Button an, beide haben aber die gleiche Funktionalität.

Später wollen wir in den BPMN Diagrammen mehrere Buttons unterstützen, die verschiedene Auswirkungen auf den Token haben können. Wie das funktionieren soll ist noch nicht spezifiziert.

- [ ] Spezifikation für die Buttons festlegen
- [ ] Spezifikation implementieren
- [ ] ???
- [ ] Profit

**Comment by Paulomart** [comment]
Fixed by 4c73eb988aba0458aac8573a9bdf15c80e3223dd
