### ISSUE TITLE
Stop Button for Process-List not implemented

### ISSUE THREAD

**Issue by Vyperus** [process-engine/charon#34]
#### Describe your issue

The stop buttons on the process-list page are disabled since there is no implementation yet.

See: https://github.com/process-engine/charon/pull/29/files#diff-74090800ce29904b22ed01173f48bfb5R97

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
As far as I know there is currently no way to stop processes using the http api. @process-engine/architects could you please clarify?

**Comment by ppoetschke** [comment]
Yes, stopping processes outside of the process logic (reaching bpmn end event) is intended to be part of a separate management api.
