### ISSUE TITLE
Reimplemented start button-href

### ISSUE THREAD

**Issue by Vyperus** [process-engine/charon#35]
#### Describe your issue

I reimplemented the "href" for the process start button as a workaround until the consumer-client is able to give back non persistent process instances.

See commit: c6b1cb6

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
Part of https://github.com/process-engine/charon/issues/22.
