### ISSUE TITLE
History reference does not work

### ISSUE THREAD

**Issue by SORC3r3r** [process-engine/charon#41]
#### Describe your issue

It is not possible to use the history reference in the processes the way it used to be before the new `consumer_client`.

Before the new `consumer_client` the decisions in my process worked with the Expression:
`this.history.<TASK_ID>.key === 'confirm'`
Now they don't.

#### How can others reproduce the issue?

Start the process with new consumer_client -> won't work as intended
Start process without consumer_client -> works fine
[issue.zip](https://github.com/process-engine/charon/files/1421223/issue.zip)

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`): Ubuntu 17.0.4
- Node (`node --version`): 7.10.1
- NPM (`npm --version`): 4.2.0
- Docker (`docker version --format '{{.Server.Version}}'`):-
- Chrome

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
I see two issues here:

1. default values are not displayed
2. history reference does not work

@SORC3r3r can you please confirm? I would like to split this issue into two separate if that is the case.

**Comment by SORC3r3r** [comment]
Yes, do as you like.

**Comment by Paulomart** [comment]
@heikomat this may be a issue with the consumer clien. Could you please take a look?

**Comment by Paulomart** [comment]
@SORC3r3r The reason that no data is display inside the message of the confirm widget is because `{{{` seems no longer supported. Instead you should do somethink like this:

```javascript
${ "message": "Value 1: " + token.history.form_data.test1 + ", Value 2: " + token.history.form_data.test2 + " ? ", "layout": [ { "key": "confirm", "label": "Approve" }, { "key": "decline", "label": "Decline", "isCancel": true } ] };
```

Im looking into the decision part now.

**Comment by heikomat** [comment]
@Paulomart @SORC3r3r this seems to be a regression introduced with the consumerClient. Your workaround should work @Paulomart, but we should discuss, if the mustache-notation-support should be added to the consumerClient @ppoetschke @zimoony

**Comment by ppoetschke** [comment]
To have compatibility with other consumer clients like the react based client I would suggest to either implement it directly in the consumer_client or at least pass it through.

**Comment by heikomat** [comment]
@ppoetschke in that case i'm for adding it to the consumerClient. as i said, it's not that hard. it just has to interpret the values before returning to the caller

**Comment by Paulomart** [comment]
@ppoetschke I dont see the mustache-notation-support as part of the consumer api. The backend should handle any formating, specially when the `$...;` is interpreted in the backend anyhow. Why did we have two formating systems in the first place? I would really make sense to just use _one_, this will porting the consumer api to other plattforms much simpler. Every small part we move into the consumer api make it more difficult to implement in other languages.

/cc @heikomat
