### ISSUE TITLE
[Feature] - start process from processDef List

### ISSUE THREAD

**Issue by SORC3r3r** [process-engine/charon#53]
#### Describe your issue

It would be nice to have a `Start` button next to the `Details` button on the processDef List.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
@SORC3r3r Done.
