### ISSUE TITLE
Configure Error Boundary Event

### ISSUE THREAD

**Issue by SORC3r3r** [process-engine/charon#66]
#### Describe your issue

It would be nice to be able to configure the error boundary events.
I´d like to configure the conditions which leads the process to follow the path of the error boundary event.
For example I want to use the error boundary event for a script task/service task (ScriptService). Sometimes I want the process to follow the boundary event path if the script has standard errors, other times I want it to follow the path of the boundary event if the exit code of the script is != 0.

Right now it seems to follow the error boundary event if the script task contains standard errors and the exit codes are ignored completely.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ppoetschke** [comment]
@SORC3r3r This is basically a feature request for the shell service, I filed an appropriate issue there https://github.com/essential-projects/services/issues/3
The process engine handles already error boundary events and no extension of charon is needed, so I will close this issue here.
