### ISSUE TITLE
html notation does not work anymore

### ISSUE THREAD

**Issue by SORC3r3r** [process-engine/charon#70]
#### Describe your issue

As of late Charon seems to not format html notations.
Before you could use line breaks or even html tables in, for example, the texts displayed in Confirm UIs.

#### How can others reproduce the issue?

Create a new process with one user task with properties:

uiName 
`Confirm`

uiConfig 
`${ "message": "First Line.<br>Second Line.", "layout": [ { "key": "confirm", "label": "Confirm"}] };`

Start the process and see the text displayed as:

`First Line.<br>Second Line.`

Instead of:

```
First Line.
Second Line.
```

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`): Ubuntu 17.0.4
- Node (`node --version`): 7.10.1
- NPM (`npm --version`): 4.2.0
- Docker (`docker version --format '{{.Server.Version}}'`):
- Chrome

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
Sounds like some `.innerHTML` was replaced with some `.innerText`. If so, this should be an easy fix

**Comment by Paulomart** [comment]
I'm concerned that we open a possible xss attack vektor here.

**Comment by ppoetschke** [comment]
As long as HTML belongs to BPMN and BPMN belongs to code, I think xss attacks are out of scope as access to BPMN models should be highly restricted.
Technically rendering is part of dynamic UI and should addressed there after reorganization of the architecture.

**Comment by SORC3r3r** [comment]
@heikomat When do you plan on fixing this?

**Comment by Vyperus** [comment]
@SORC3r3r I made an easy Fix for this in my PR today ;)
