### ISSUE TITLE
start next user task directly after previous task if in the same lane

### ISSUE THREAD

**Issue by SORC3r3r** [process-engine/charon#71]
#### Describe your issue

Is it possible to configure Charon to directly start the next user task if it is in the same lane as the user task before?
Currently after finishing a user task, the task list is displayed and you have to navigate in the next user task manually.

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`): Ubuntu
- Node (`node --version`): 7.10.1
- NPM (`npm --version`): 4.2.0
- Docker (`docker version --format '{{.Server.Version}}'`):
- Chrome

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
We solved this by adding a kind of "waiting room".
See #80
