### ISSUE TITLE
Cannot create a new ProcessDef/ProcessModel from dashboard

### ISSUE THREAD

**Issue by moellenbeck** [process-engine/charon#76]
#### Describe your issue

Cannot create a new ProcessDef/ProcessModel from dashboard button `Create Process Definition`.

#### How can others reproduce the issue?

- Login 
- Go to charon dashboard
- Click `Create Process Definition`
- See attachments

![bildschirmfoto 2017-12-09 um 11 02 59](https://user-images.githubusercontent.com/169372/33794684-917a8230-dcd0-11e7-88b0-3b01285e9b13.jpg)

![bildschirmfoto 2017-12-09 um 11 03 03](https://user-images.githubusercontent.com/169372/33794687-954f5340-dcd0-11e7-8374-0f8a7ea45d72.jpg)

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`): macOS High Sierra
- Browser:  Safari

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
I first thought that this was due to process-engine/consumer_client/issues/2, but while this is part of the issue, this wouldn't completely fix it. from what i can see:

- if you press the button, you get "no UserTask found" and a 500 with `{"error":"Error: Error: Entity could not be found"}`
- if you then however refresh the page (with the task-id in the url), you get the correct userTask!

**Comment by heikomat** [comment]
This seems to be a timing or caching problem within the process-engine:

When i slow down my browser, so that charon is slower, this issue doesn't happen

![ezgif-5-ffe671be32](https://user-images.githubusercontent.com/20770029/33876312-7894b04a-df25-11e7-86d8-c21049145c6b.gif)

**Comment by heikomat** [comment]
This is indeed not a charon bug, but a combination of these bugs:

- https://github.com/process-engine/consumer_client/issues/2
- https://github.com/process-engine/process_engine/issues/30

If both of these are fixed, this will be too.
