### ISSUE TITLE
UI flows not intuitive - sometimes the user is delegated to the "wrong" dialog

### ISSUE THREAD

**Issue by moellenbeck** [process-engine/charon#79]
#### Describe your issue

- We need a concept what should happens next (BPMN-Diagrams)
- Test the current flow and fix it

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`): macOS High Sierra
- Browser: Safari

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [ ] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ppoetschke** [comment]
@moellenbeck Do you have a more self explaining example?

**Comment by heikomat** [comment]
a quick idea:

- When the userTask is finished, the user gets a waiting-animation and a "go back"-button
- if a new userTask for the same process happens, the waiting icon disappeares and the userTask will be shown directly
- if the process ends, the waiting-icon disappeares and a "process ended"-like text appeares
