### ISSUE TITLE
🌐 Translate Charon Fully to English

### ISSUE THREAD

**Issue by Paulomart** [process-engine/charon#88]
#### Describe your issue

In some parts of the application are _still_ german text messages. Often in *.ts files. 

#### How can others reproduce the issue?

For example: Clicking `Save` on the processdef-detail page alerts `Gespeichert`

#### Possible solution

Translate all messages to english

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
I did the review an corrected the spelling.
