### ISSUE TITLE
Too Many Interfaces in one File

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/charon#95]
## Describe your issue

Too many interfaces in one file:

https://github.com/process-engine/charon/pull/84/files/4031cbae976e85547af1b2858bbd4a78edd3deda#diff-efcd084c4db3f5bd8e8dddf65a5c5e57

## How can others reproduce the issue?

Check out the link above.

## Possible solution

Separate the interfaces in the contracts module.

**What we agreed on:**

1. We separate **each** interface in its own .ts file
1. We **do not** place implementation directly next to the interfaces
1. We **prepend** a capital i to each interface
1. We **add** a folder structure to keep semantic context

   Example (taken from another Project):

   ```
   hierachical_objects/contracts/
                                 IRepository.ts
                                 IService.ts
                                 hierachicalObject.ts
   ```

   The implementation would lie in `hierachical_objects/xyz` folder.

   Other example is: IAM

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [ ] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
The interfaces are seperated by topics. @Paulomart mentioned this on https://github.com/process-engine/charon/pull/101

**Comment by cmg-dev** [comment]
@Vyperus @Paulomart i updated the issue description.

**Comment by Vyperus** [comment]
@cmg-dev 👍
